spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
  jpa:
    #show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    #open-in-view: false

  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql:userbook

#logging.level.org.hibernate: DEBUG
#logging.level.org.springframework: DEBUG